### ISSUE TITLE
but will it work for sparse binary data with ones 10% and  zeros  90%?

### ISSUE THREAD

**Issue by Sandy4321** [gumeo/accSDA#4]
great code thanks

but will it work for sparse binary data with ones 10% and  zeros  90%?
when ones is 10% of data
and 0s are 90% of data ?

**Comment by gumeo** [comment]
Hi @Sandy4321 imbalanced data is generally an issue. I would look for how this problem is solved for linear discriminant analysis (LDA) to get ideas for how to approach this problem.
